// Package aes implements the AES-256-GCM envelope transport documented in
// docs/AES-TRANSPORT.md. It is the no-TLS path for embedded clients (ESP32,
// STM32, …) that cannot afford a TLS stack but can run an AES-GCM
// implementation alongside an HTTP client.
//
// Wire shape (request):
//
//	POST /aes/<route> HTTP/1.1
//	Sec-CIB-Envelope: 1
//	Sec-CIB-KeyId:    <device key id>
//	Sec-CIB-Nonce:    <24 hex chars; 12 raw bytes>
//	Sec-CIB-Timestamp:<unix_millis>
//	Content-Type:     application/octet-stream
//
//	<ciphertext || 16-byte gcm tag>
//
// AAD binds the envelope to a single (method, route, key, timestamp), so the
// same ciphertext cannot be replayed against another endpoint or method.
package aes

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"
)

const (
	EnvelopeVersion = "1"
	NonceLen        = 12
	TagLen          = 16
	KeyLen          = 32 // AES-256-GCM

	HeaderEnvelope  = "Sec-CIB-Envelope"
	HeaderKeyID     = "Sec-CIB-KeyId"
	HeaderNonce     = "Sec-CIB-Nonce"
	HeaderTimestamp = "Sec-CIB-Timestamp"
)

// Headers is the per-request envelope metadata. Decoded from the
// `Sec-CIB-*` headers by ParseHeaders, generated by NewHeaders for tests
// and the device-side client SDKs.
type Headers struct {
	Envelope   string
	KeyID      string
	Nonce      [NonceLen]byte
	NonceHex   string
	TimestampMillis int64
}

// ParseHeaders extracts the envelope metadata from an *http.Request and
// validates the shape. It does NOT validate the timestamp drift or replay —
// those checks live in ReplayCache.
func ParseHeaders(r *http.Request) (Headers, error) {
	h := Headers{
		Envelope: r.Header.Get(HeaderEnvelope),
		KeyID:    r.Header.Get(HeaderKeyID),
		NonceHex: r.Header.Get(HeaderNonce),
	}
	if h.Envelope != EnvelopeVersion {
		return h, fmt.Errorf("aes: unsupported %s=%q (want %q)", HeaderEnvelope, h.Envelope, EnvelopeVersion)
	}
	if h.KeyID == "" {
		return h, fmt.Errorf("aes: missing %s", HeaderKeyID)
	}
	if h.NonceHex == "" {
		return h, fmt.Errorf("aes: missing %s", HeaderNonce)
	}
	nonceBytes, err := hex.DecodeString(h.NonceHex)
	if err != nil || len(nonceBytes) != NonceLen {
		return h, fmt.Errorf("aes: %s must be %d hex chars (%d raw bytes)", HeaderNonce, NonceLen*2, NonceLen)
	}
	copy(h.Nonce[:], nonceBytes)

	tsStr := r.Header.Get(HeaderTimestamp)
	ts, err := strconv.ParseInt(tsStr, 10, 64)
	if err != nil {
		return h, fmt.Errorf("aes: %s must be unix millis: %v", HeaderTimestamp, err)
	}
	h.TimestampMillis = ts
	return h, nil
}

// NewHeaders generates a fresh Headers with a random nonce and the current
// time. Used by the test client and by the reference Go client.
func NewHeaders(keyID string) (Headers, error) {
	h := Headers{
		Envelope:        EnvelopeVersion,
		KeyID:           keyID,
		TimestampMillis: time.Now().UTC().UnixMilli(),
	}
	if _, err := rand.Read(h.Nonce[:]); err != nil {
		return h, err
	}
	h.NonceHex = hex.EncodeToString(h.Nonce[:])
	return h, nil
}

// Apply writes the envelope headers onto r.Header. Used by the reference
// Go client.
func (h Headers) Apply(r *http.Request) {
	r.Header.Set(HeaderEnvelope, h.Envelope)
	r.Header.Set(HeaderKeyID, h.KeyID)
	r.Header.Set(HeaderNonce, h.NonceHex)
	r.Header.Set(HeaderTimestamp, strconv.FormatInt(h.TimestampMillis, 10))
	r.Header.Set("Content-Type", "application/octet-stream")
}

// AAD builds the associated-data bytes that bind the envelope to a single
// request. Format:
//
//	CIB1\n<KeyId>\n<Timestamp>\n<Method>\n<Route>\n
//
// For responses, callers pass method="RESPONSE" so request and response
// envelopes are not interchangeable.
func AAD(h Headers, method, route string) []byte {
	var b strings.Builder
	b.WriteString("CIB")
	b.WriteString(EnvelopeVersion)
	b.WriteByte('\n')
	b.WriteString(h.KeyID)
	b.WriteByte('\n')
	b.WriteString(strconv.FormatInt(h.TimestampMillis, 10))
	b.WriteByte('\n')
	b.WriteString(method)
	b.WriteByte('\n')
	b.WriteString(route)
	b.WriteByte('\n')
	return []byte(b.String())
}

// Open decrypts `ciphertext` with `key` and verifies the GCM tag, using the
// envelope-bound AAD. Returns the plaintext on success.
func Open(key []byte, h Headers, method, route string, ciphertext []byte) ([]byte, error) {
	if len(key) != KeyLen {
		return nil, fmt.Errorf("aes: key length must be %d, got %d", KeyLen, len(key))
	}
	if len(ciphertext) < TagLen {
		return nil, errors.New("aes: ciphertext shorter than tag")
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	return gcm.Open(nil, h.Nonce[:], ciphertext, AAD(h, method, route))
}

// Seal is the inverse of Open. It also takes Headers so the AAD matches
// what the recipient will use to validate.
func Seal(key []byte, h Headers, method, route string, plaintext []byte) ([]byte, error) {
	if len(key) != KeyLen {
		return nil, fmt.Errorf("aes: key length must be %d, got %d", KeyLen, len(key))
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	return gcm.Seal(nil, h.Nonce[:], plaintext, AAD(h, method, route)), nil
}
