#!/usr/bin/env bash
# Drop a self-signed cert + nginx server block in front of the test box so
# the Web UI is reachable over HTTPS.
#
# Run ON the remote host as root.
#
#   ./remote-https.sh cib.hk1.clawf.run  # serves https://<domain>/
#   ./remote-https.sh                    # defaults to cib.hk1.clawf.run
#
# Assumes:
#  - cib container is already up on host port 8090 (see remote-deploy.sh)
#  - nginx 1.18+ is running with /etc/nginx/conf.d/ included
#  - DNS for <domain> resolves to this host's public IP
#
# The cert is intentionally self-signed; the user accepts the browser
# warning once. Replace with a real Let's Encrypt cert when you have DNS
# under your own control.
set -euo pipefail

DOMAIN="${1:-a.hk1.clawf.run}"
PORT="${CIB_HOST_PORT:-8090}"
TLS_PORT="${CIB_TLS_PORT:-8443}"  # avoid 443 if another nginx wildcard
                                  # owns *.hk1.clawf.run on this host
DAYS="${CIB_CERT_DAYS:-825}"      # max for self-signed accepted by macOS
CERT_DIR=/etc/claude-in-box/tls

log() { printf '[remote-https] %s\n' "$*" >&2; }

mkdir -p "$CERT_DIR"
chmod 700 "$CERT_DIR"

if [[ ! -s "$CERT_DIR/cib.crt" ]]; then
    log "minting self-signed cert for ${DOMAIN}, ${DAYS} days"
    openssl req -x509 -nodes -newkey rsa:2048 \
        -days "$DAYS" \
        -keyout "$CERT_DIR/cib.key" \
        -out    "$CERT_DIR/cib.crt" \
        -subj   "/CN=${DOMAIN}/O=claude-in-box/OU=test" \
        -addext "subjectAltName=DNS:${DOMAIN}" \
        >/dev/null 2>&1
    chmod 600 "$CERT_DIR/cib.key"
else
    log "reusing existing cert at $CERT_DIR/cib.crt"
fi

CONF=/etc/nginx/conf.d/cib-test.conf
log "writing $CONF (TLS on :${TLS_PORT} to avoid clashing with the wildcard nginx on 443)"
cat > "$CONF" <<NGINX
# claude-in-box test deployment — auto-generated by scripts/remote-https.sh
upstream cib_backend {
    server 127.0.0.1:${PORT};
    keepalive 32;
}

map \$http_upgrade \$cib_connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen ${TLS_PORT} ssl http2 default_server;
    listen [::]:${TLS_PORT} ssl http2 default_server;
    server_name _;

    ssl_certificate     ${CERT_DIR}/cib.crt;
    ssl_certificate_key ${CERT_DIR}/cib.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Large bodies for tool outputs, screenshots, etc.
    client_max_body_size 64m;
    proxy_request_buffering off;
    proxy_buffering off;

    # WebSocket endpoints — /ws/sessions/* + /ws/shells/*
    location ~ ^/ws/ {
        proxy_pass http://cib_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade            \$http_upgrade;
        proxy_set_header Connection         \$cib_connection_upgrade;
        proxy_set_header Host               \$host;
        proxy_set_header X-Real-IP          \$remote_addr;
        proxy_set_header X-Forwarded-For    \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  \$scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # SSE
    location ~ ^/sse/ {
        proxy_pass http://cib_backend;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400;
        chunked_transfer_encoding off;
        add_header X-Accel-Buffering no always;
    }

    # AES envelope (binary bodies; do not buffer / gzip)
    location /aes/ {
        proxy_pass http://cib_backend;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_buffering off;
        gzip off;
    }

    # REST + Web UI
    location / {
        proxy_pass http://cib_backend;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection        "";
    }
}
NGINX

log "validating nginx config"
nginx -t

log "reloading nginx"
systemctl reload nginx

log "done — https://${DOMAIN}:${TLS_PORT}/ should now resolve to the box"
log "fingerprint of the self-signed cert (sha256):"
openssl x509 -in "$CERT_DIR/cib.crt" -noout -fingerprint -sha256 | sed 's/^/  /'
